# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mintRailsProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mintRailsProject
    pod 'SnapKit'

  target 'mintRailsProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mintRailsProjectUITests' do
    # Pods for testing
  end

end
